spring:
  profiles: docker
  datasource:
    url: 'jdbc:h2:file:./target/database/h2'
    #url: jdbc:h2:mem:test_mem
    username: sa
    password: null
    driverClassName: org.h2.Driver
    max-active: 15
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirH2Dialect
hapi:
  fhir:
    tester:
      home:
        server_address: 'http://host.docker.internal:8080/fhir'
basic-auth:
  status: true
  admin-user: admin
  admin-password: admin
  human-user: human
  human-password: human